=== MrParkerZ7/21stepbase/src/main/java/xml/dtd_structural_grammar/KillerType.dtd
<?xml version="1.0" encoding="UTF-8" ?>

        <!ELEMENT killers (killer+)>
        <!ELEMENT killer (name,weapon,bounty)>
        <!ELEMENT name (#PCDATA)>
        <!ELEMENT weapon (#PCDATA)>
        <!ELEMENT bounty (#PCDATA)>

        <!--Required-->
        <!ATTLIST killer id ID #REQUIRED>
        <!--Optional-->
        <!ATTLIST killer lang (EN|TH|Kotlin|Java) "EN")>

=== MrParkerZ7/21stepbase/src/main/java/xml/dtd_structural_grammar/Killer.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE killers SYSTEM "KillerType.dtd">

<killers>
    <killer id="1" lang="TH">
        <name>Park</name>
        <weapon>Sword</weapon>
        <bounty>70à¸¿</bounty>
    </killer>
    <killer id="2" lang="Kotlin">
        <name>Micro</name>
        <weapon>Lightning</weapon>
        <bounty>700000$</bounty>
    </killer>
    <killer id="3">
        <name>Sigma</name>
        <weapon>Sniper</weapon>
        <bounty>500000$</bounty>
    </killer>
</killers>
